[package]
name = "collections-enums"
version = "0.1.0"
authors = ["Attila Bakos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.5"
