[package]
name = "std-lib"
version = "0.1.0"
authors = ["a-bakos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
